### ISSUE TITLE
hanami-cli 2.alpha6 does not word because of removed method init_bootable

### ISSUE THREAD

**Issue by vieteh** [hanami/cli#10]
Current version of hanami-cli-2.0.0.alpha6 does not work

Eg, run command `./bin/hanami db migrate` causes the exception

```
.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/hanami-cli-2.0.0.alpha6/lib/hanami/cli/commands/db/utils/database.rb:72:in `rom_config': undefined method `init_bootable' for MyApp::Application:Class (NoMethodError)
        from .asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/hanami-cli-2.0.0.alpha6/lib/hanami/cli/commands/db/utils/database.rb:82:in `gateway'
        from .asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/hanami-cli-2.0.0.alpha6/lib/hanami/cli/commands/db/utils/database.rb:91:in `run_migrations'
        from .asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/hanami-cli-2.0.0.alpha6/lib/hanami/cli/commands/monolith/db/migrate.rb:33:in `run_migrations'
        from .asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/hanami-cli-2.0.0.alpha6/lib/hanami/cli/commands/monolith/db/migrate.rb:23:in `block in call'
        from .asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/hanami-cli-2.0.0.alpha6/lib/hanami/cli/commands/application.rb:43:in `measure'
        from .asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/hanami-cli-2.0.0.alpha6/lib/hanami/cli/commands/monolith/db/migrate.rb:19:in `call'
        from .asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/hanami-cli-2.0.0.alpha6/lib/hanami/cli/commands/application.rb:15:in `call'
        from .asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/dry-cli-0.7.0/lib/dry/cli.rb:116:in `perform_registry'
        from .asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/dry-cli-0.7.0/lib/dry/cli.rb:65:in `call'
        from .asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/hanami-cli-2.0.0.alpha6/exe/hanami:10:in `<top (required)>'
        from ./bin/hanami:29:in `load'
        from ./bin/hanami:29:in `<main>'
```

**Comment by jodosha** [comment]
Fixed by #11
