### ISSUE TITLE
hanami db version fails on unapplied migration

### ISSUE THREAD

**Issue by tak1n** [hanami/cli#16]
Hi there, I'm currently taking a stab at implementing something like rails' `db:abort_if_pending_migrations` which is quite useful in certain [scenarios](https://thoughtbot.com/blog/zero-downtime-rails-deployments-with-kubernetes). While doing so I spotted some weird behaviour which I will try to fix, but thought I open a separate GH issue for documentation purposes.

Whenever a new migration is created the command `hanami db version` fails. After applying the migration the command works again. 

```
hanami-timetracker on  main [!?] is 📦 v1.0.0 via ⬢ v16.14.2 via 💎 v3.1.2 on 🐳 v20.10.14 
➜ hanami db reset
=> database timetracker dropped
=> database timetracker created
=> database timetracker migrated in 0.2788s

hanami-timetracker on  main [!?] is 📦 v1.0.0 via ⬢ v16.14.2 via 💎 v3.1.2 on 🐳 v20.10.14 
➜ hanami db version                             
=> current schema version is 20220422184849_create_items_table

hanami-timetracker on  main [!?] is 📦 v1.0.0 via ⬢ v16.14.2 via 💎 v3.1.2 on 🐳 v20.10.14 
➜ hanami db create_migration test_migration
=> migration 20220426195743_test_migration created in 0.0001s

hanami-timetracker on  main [!?] is 📦 v1.0.0 via ⬢ v16.14.2 via 💎 v3.1.2 on 🐳 v20.10.14 
➜ hanami db version
/home/benjamin/.gem/ruby/3.1.2/gems/rom-sql-3.5.0/lib/rom/sql/migration.rb:62:in `migration': undefined method `migration' for nil:NilClass (NoMethodError)

          current_gateway.migration(&block)
                         ^^^^^^^^^^
        from /home/benjamin/dev/github/hanami-timetracker/db/migrate/20220426195743_test_migration.rb:3:in `<top (required)>'
        from /home/benjamin/.gem/ruby/3.1.2/gems/sequel-5.55.0/lib/sequel/extensions/migration.rb:493:in `load'
        from /home/benjamin/.gem/ruby/3.1.2/gems/sequel-5.55.0/lib/sequel/extensions/migration.rb:493:in `block in load_migration_file'
        from /home/benjamin/.gem/ruby/3.1.2/gems/sequel-5.55.0/lib/sequel/extensions/migration.rb:491:in `synchronize'
        from /home/benjamin/.gem/ruby/3.1.2/gems/sequel-5.55.0/lib/sequel/extensions/migration.rb:491:in `load_migration_file'
        from /home/benjamin/.gem/ruby/3.1.2/gems/sequel-5.55.0/lib/sequel/extensions/migration.rb:763:in `block in get_migration_tuples'
        from /home/benjamin/.gem/ruby/3.1.2/gems/sequel-5.55.0/lib/sequel/extensions/migration.rb:751:in `each'
        from /home/benjamin/.gem/ruby/3.1.2/gems/sequel-5.55.0/lib/sequel/extensions/migration.rb:751:in `get_migration_tuples'
        from /home/benjamin/.gem/ruby/3.1.2/gems/sequel-5.55.0/lib/sequel/extensions/migration.rb:680:in `initialize'
        from /home/benjamin/.gem/ruby/3.1.2/bundler/gems/cli-752cc5d64bbd/lib/hanami/cli/commands/db/utils/database.rb:114:in `new'
        from /home/benjamin/.gem/ruby/3.1.2/bundler/gems/cli-752cc5d64bbd/lib/hanami/cli/commands/db/utils/database.rb:114:in `sequel_migrator'
        from /home/benjamin/.gem/ruby/3.1.2/bundler/gems/cli-752cc5d64bbd/lib/hanami/cli/commands/db/utils/database.rb:105:in `applied_migrations'
        from /home/benjamin/.gem/ruby/3.1.2/bundler/gems/cli-752cc5d64bbd/lib/hanami/cli/commands/monolith/db/version.rb:16:in `call'
        from /home/benjamin/.gem/ruby/3.1.2/bundler/gems/cli-752cc5d64bbd/lib/hanami/cli/commands/application.rb:19:in `call'
        from /home/benjamin/.gem/ruby/3.1.2/gems/dry-cli-0.7.0/lib/dry/cli.rb:116:in `perform_registry'
        from /home/benjamin/.gem/ruby/3.1.2/gems/dry-cli-0.7.0/lib/dry/cli.rb:65:in `call'
        from /home/benjamin/.gem/ruby/3.1.2/gems/hanami-cli-2.0.0.alpha7/exe/hanami:10:in `<top (required)>'
        from /home/benjamin/.gem/ruby/3.1.2/bin/hanami:25:in `load'
        from /home/benjamin/.gem/ruby/3.1.2/bin/hanami:25:in `<main>'

hanami-timetracker on  main [!?] is 📦 v1.0.0 via ⬢ v16.14.2 via 💎 v3.1.2 on 🐳 v20.10.14 
➜ hanami db migrate
=> database timetracker migrated in 0.2391s

hanami-timetracker on  main [!?] is 📦 v1.0.0 via ⬢ v16.14.2 via 💎 v3.1.2 on 🐳 v20.10.14 
➜ hanami db version
=> current schema version is 20220426195743_test_migration
```

I'm facing the same issue for the new command I'm trying to implement and will investigate why this is appearing.

**EDIT:** 

Using `hanami-cli` github `main` branch.

```ruby
# frozen_string_literal: true

source "https://rubygems.org/"

# Core gems
gem "rake", "~> 13.0"

# Application framework
gem "hanami", "~> 2.0.0.alpha"
# gem "hanami-cli", "~> 2.0.0.alpha"
gem "hanami-cli", github: "hanami/cli"
# gem "hanami-cli", path: "../cli"
gem "hanami-controller", "~> 2.0.alpha"
gem "hanami-router", "~> 2.0.0.alpha"
gem "hanami-utils", "~> 2.0.0.alpha"
gem "hanami-view", "~> 2.0.0.alpha"
```

**Comment by jodosha** [comment]
@tak1n Hey Ben thanks for reporting this problem. Please remember that CLI isn't fully working yet in Hanami 2. This is especially true for db commands because of missing ROM integration. This integration will be implemented soon.
