### ISSUE TITLE
Cli error on "hanami new" -- cannot load such file -- hanami/router/inspector

### ISSUE THREAD

**Issue by cpgo** [hanami/cli#28]
Following the steps on the [beta annoucement](https://hanamirb.org/blog/2022/07/20/announcing-hanami-200beta1/) gives me an error 

```
❯ ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

❯ gem install hanami --pre

❯ hanami new bookshelf    
<internal:/home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- hanami/router/inspector (LoadError)
        from <internal:/home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app/routes.rb:4:in `<top (required)>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:11:in `require_relative'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:11:in `<module:App>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:6:in `<module:Commands>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:5:in `<module:CLI>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:4:in `<module:Hanami>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:3:in `<top (required)>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands.rb:15:in `require_relative'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands.rb:15:in `register_commands!'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli.rb:14:in `<module:CLI>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli.rb:6:in `<module:Hanami>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli.rb:5:in `<top (required)>'
        from <internal:/home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/exe/hanami:5:in `<top (required)>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/bin/hanami:25:in `load'
        from /home/cassio/.asdf/installs/ruby/3.1.2/bin/hanami:25:in `<main>'
```

**Comment by jodosha** [comment]
@cpgo Thanks for reporting this.

What the following command returns to you?

```shell
gem --list | grep hanami
```

**Comment by waiting-for-dev** [comment]
Thanks for reporting. Probably, you can work around it by adding `hanami/router` to the Gemfile.

**Comment by jodosha** [comment]
@waiting-for-dev `hanami-router` is added to the `Gemfile` by `hanami new`.

**Comment by jodosha** [comment]
@cpgo Could you please do:

```
hanami new bookshelf --skip-bundle
cd bookshelf
bundle install # I expect this step to work
bundle exec hanami install # this is the one that crashes
cat Gemfile.lock | pbpaste
```

Please paste the `Gemfile.lock` contents as a comment in this GH issue.

Thanks.

**Comment by cpgo** [comment]
Hi @jodosha, the command `hanami new bookshelf --skip-bundle` triggers the same error.
Even running the bare `hanami` command with no options does it
```
❯ hanami new bookshelf --skip-bundle
<internal:/home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- hanami/router/inspector (LoadError)
        from <internal:/home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app/routes.rb:4:in `<top (required)>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:11:in `require_relative'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:11:in `<module:App>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:6:in `<module:Commands>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:5:in `<module:CLI>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:4:in `<module:Hanami>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:3:in `<top (required)>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands.rb:15:in `require_relative'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands.rb:15:in `register_commands!'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli.rb:14:in `<module:CLI>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli.rb:6:in `<module:Hanami>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli.rb:5:in `<top (required)>'
        from <internal:/home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/exe/hanami:5:in `<top (required)>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/bin/hanami:25:in `load'
        from /home/cassio/.asdf/installs/ruby/3.1.2/bin/hanami:25:in `<main>'


❯ hanami                            
<internal:/home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- hanami/router/inspector (LoadError)
        from <internal:/home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app/routes.rb:4:in `<top (required)>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:11:in `require_relative'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:11:in `<module:App>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:6:in `<module:Commands>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:5:in `<module:CLI>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:4:in `<module:Hanami>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands/app.rb:3:in `<top (required)>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands.rb:15:in `require_relative'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli/commands.rb:15:in `register_commands!'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli.rb:14:in `<module:CLI>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli.rb:6:in `<module:Hanami>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/lib/hanami/cli.rb:5:in `<top (required)>'
        from <internal:/home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/cassio/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/hanami-cli-2.0.0.beta1/exe/hanami:5:in `<top (required)>'
        from /home/cassio/.asdf/installs/ruby/3.1.2/bin/hanami:25:in `load'
        from /home/cassio/.asdf/installs/ruby/3.1.2/bin/hanami:25:in `<main>'
```

**Comment by jodosha** [comment]
@cpgo From the directory where you generate the Bookshelf app, do you have a file named `config/app.rb`?

**Comment by cpgo** [comment]
Ohhhh
Not a `config/app.rb` but I had an unrelated `app.rb`.
Deleting that file fixed the issue.

**Comment by jodosha** [comment]
@cpgo This is the culprit https://github.com/hanami/cli/blob/main/lib/hanami/cli/commands.rb#L5-L8

We need to switch between the commands **outside** of an app (`hanami version` and `hanami new`) vs **inside** an app (`hanami routes`, `hanami server`, etc..).

That logic linked above is too brittle.
