### ISSUE TITLE
[2.0.0alpha2] cannot load such file -- hanami/version

### ISSUE THREAD

**Issue by masterkain** [hanami/cli#3]
I'm upgrading a rails app to ruby 3.0, I had an issue with stable versions of hanami-cli so I tried to upgrade to the 2.0.0alpha2, I get this:

```
/bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/generators/context.rb:3:in `require': cannot load such file -- hanami/version (LoadError)
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/generators/context.rb:3:in `<top (required)>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/generators/monolith/slice_context.rb:3:in `require_relative'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/generators/monolith/slice_context.rb:3:in `<top (required)>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/generators/monolith/slice.rb:5:in `require'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/generators/monolith/slice.rb:5:in `<top (required)>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith/generate/slice.rb:4:in `require'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith/generate/slice.rb:4:in `<top (required)>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith/generate.rb:8:in `require_relative'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith/generate.rb:8:in `<module:Generate>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith/generate.rb:7:in `<module:Monolith>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith/generate.rb:6:in `<module:Commands>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith/generate.rb:5:in `<module:CLI>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith/generate.rb:4:in `<module:Hanami>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith/generate.rb:3:in `<top (required)>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith.rb:11:in `require_relative'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith.rb:11:in `<module:Monolith>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith.rb:6:in `<module:Commands>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith.rb:5:in `<module:CLI>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith.rb:4:in `<module:Hanami>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands/monolith.rb:3:in `<top (required)>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands.rb:16:in `require_relative'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli/commands.rb:16:in `register_commands!'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli.rb:14:in `<module:CLI>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli.rb:6:in `<module:Hanami>'
	from /bundle/vendor/ruby/3.0.0/gems/hanami-cli-2.0.0.alpha2/lib/hanami/cli.rb:5:in `<top (required)>'
```

**Comment by jodosha** [comment]
@masterkain What Rails has to do with `hanami-cli`? 🙂

**Comment by masterkain** [comment]
nothing directly, it happened that one of our gems had a hard dependency on `hanami-cli`, when I tried to upgrade it to a newer version I had the issue above -- I mentioned the rails context maybe because it had something to do with zeitwerk or ruby version

**Comment by jodosha** [comment]
Got it. 🙂 
Which gem was that?
