### ISSUE TITLE
Can't generate a new project

### ISSUE THREAD

**Issue by volodymyro-in6k** [hanami/cli#41]
Hi, 
I'm new here. so, i'm trying to generate a project from the main page example.
http://hanamirb.org/#install

**OS**: ubuntu 16.04
**Ruby**: 2.3.0
**Hanami**: 1.2.0

**Here is output:**
```
hanami new test-project
wrong number of arguments (given 0, expected 2..3)
(erb):2:in `test'
	(erb):2:in `binding'
	/home/user/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `eval'
	/home/user/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `result'
	/home/user/.rvm/gems/ruby-2.3.0/gems/hanami-1.2.0/lib/hanami/cli/commands/command.rb:123:in `call'
	/home/user/.rvm/gems/ruby-2.3.0/gems/hanami-1.2.0/lib/hanami/cli/commands/command.rb:149:in `render'
	/home/user/.rvm/gems/ruby-2.3.0/gems/hanami-1.2.0/lib/hanami/cli/commands/command.rb:157:in `generate_file'
	/home/user/.rvm/gems/ruby-2.3.0/gems/hanami-1.2.0/lib/hanami/cli/commands/new.rb:554:in `generate_file'
	/home/user/.rvm/gems/ruby-2.3.0/gems/hanami-1.2.0/lib/hanami/cli/commands/new.rb:347:in `generate_application_templates'
	/home/user/.rvm/gems/ruby-2.3.0/gems/hanami-1.2.0/lib/hanami/cli/commands/new.rb:315:in `block in call'
	/home/user/.rvm/gems/ruby-2.3.0/gems/hanami-1.2.0/lib/hanami/cli/commands/new.rb:314:in `chdir'
	/home/user/.rvm/gems/ruby-2.3.0/gems/hanami-1.2.0/lib/hanami/cli/commands/new.rb:314:in `call'
	/home/user/.rvm/gems/ruby-2.3.0/gems/hanami-1.2.0/lib/hanami/cli/commands/command.rb:85:in `call'
	/home/user/.rvm/gems/ruby-2.3.0/gems/hanami-cli-0.2.0/lib/hanami/cli.rb:57:in `call'
	/home/user/.rvm/gems/ruby-2.3.0/gems/hanami-1.2.0/bin/hanami:6:in `<top (required)>'
	/home/user/.rvm/gems/ruby-2.3.0/bin/hanami:23:in `load'
	/home/user/.rvm/gems/ruby-2.3.0/bin/hanami:23:in `<main>'
	/home/user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	/home/user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

Thank you.
Let me know if you need more information

**Comment by AlfonsoUceda** [comment]
Hi @volodymyro-in6k thanks for the issue, yes it fails in ruby 2.3.0, check this failed job in travis https://travis-ci.org/hanami/hanami/jobs/399004854

Can't you use ruby 2.3.4? the problem doesn't exist in that version.

**Comment by AlfonsoUceda** [comment]
Closing this issue
